name: alhalama
favicon: null
layout_spectrum: 0.5780955008231103
typography_spectrum: 0.6556636858731508
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9433127741795033
  lightness: 0.07337705581448972
  saturation: 0.8481069603003561
  rhythmicContrast: 0.32900332496501505
purpose: []
